/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mouse_MouseCursor */

#ifndef _Included_mouse_MouseCursor
#define _Included_mouse_MouseCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mouse_MouseCursor
 * Method:    GetCursorPos
 * Signature: ()[J
 */
JNIEXPORT jdoubleArray JNICALL Java_mouse_MouseCursor_GetCursorPos
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
